import type { Post } from "./blog";

/** Puni vodiči po destinacijama (blog postovi za slugove iz lib/guides.ts).
 *  Pišu se u repozitorijumu i objavljuju sa sajtom — ne zavise od baze.
 *  Spajaju se u lib/blog.ts zajedno sa STATIC_POSTS. */
export const GUIDE_POSTS: Post[] = [
  {
    id: "guide-banja-vrujci",
    slug: "banja-vrujci-vodic",
    category: "banje-i-wellness",
    cover_image: "https://images.unsplash.com/photo-1540206395-68808572332f?auto=format&fit=crop&w=1600&q=80",
    status: "published",
    created_at: "2026-07-20T09:00:00Z",
    updated_at: null,
    title_sr: "Banja Vrujci: vodič za odmor na sat vožnje od Beograda",
    title_en: "Banja Vrujci: a guide to a spa break an hour from Belgrade",
    title_de: "Banja Vrujci: Reiseführer für einen Kurzurlaub eine Stunde von Belgrad",
    excerpt_sr: "Termalna voda od 26–28 °C, bazeni, brvnare i mir podno Suvobora — kako do Vrujaca, kada ići, gde odsesti i šta videti u okolini.",
    excerpt_en: "Thermal water at 26–28 °C, pools, log cabins and quiet below Suvobor — how to reach Vrujci, when to go, where to stay and what to see nearby.",
    excerpt_de: "Thermalwasser mit 26–28 °C, Becken, Blockhütten und Ruhe unter dem Suvobor — Anreise, beste Zeit, Unterkunft und Ausflüge.",
    body_sr: "Banja Vrujci leži u dolini reke Toplice, u opštini Mionica, na oko sat i po vožnje jugozapadno od Beograda. Poznata je po termalnoj vodi umerene temperature, otvorenim i zatvorenim bazenima i mirnom, porodičnom ambijentu podno Suvobora i Rajca. Za razliku od velikih lečilišta, Vrujci su pre svega mesto za opuštanje, kupanje i vikend odmor sa decom.\n\n## Termalna voda i bazeni\n\nIzvori Vrujaca daju vodu temperature oko 26–28 °C, blago mineralizovanu, prijatnu za kupanje tokom cele godine. Oko banje je nekoliko kompleksa sa otvorenim bazenima koji rade leti, dok pojedini objekti imaju zatvorene, grejane bazene i manje wellness sadržaje. Voda se tradicionalno koristi za opuštanje mišića i zglobova, ali većina gostiju dolazi jednostavno zbog kupanja i mira.\n\n## Kada ići\n\nGlavna sezona je od maja do septembra, kada rade otvoreni bazeni i kada je okolina najlepša za šetnju i vožnju bicikla. Vrujci su, međutim, prijatni i van sezone: brvnare i vikendice sa sopstvenim grejanjem popularne su za zimske vikende, a okolni Suvobor i Rajac privlače planinare tokom cele godine.\n\n## Kako stići\n\nIz Beograda se najbrže stiže autoputem do Lajkovca, pa lokalnim putem preko Mionice — ukupno oko 90 do 100 kilometara. Automobil je najpraktičniji jer omogućava obilazak okoline, ali do Mionice postoji i autobuska veza, uz lokalni prevoz do same banje. Više o opcijama ima u tekstu o [prevozu i autoprevoznicima](/blog/autoprevoznici-i-kombi-prevoz-srbija-inostranstvo).\n\n## Gde odsesti\n\nPonuda smeštaja u Vrujcima je raznovrsna: od soba i apartmana u centru banje do [brvnara i koliba](/brvnare-i-kolibe) i [vikendica](/vikendice) po okolnim brdima. Za porodice sa decom praktični su objekti sa sopstvenim bazenom i dvorištem, a za mirniji odmor biraju se brvnare izvan centra. Pogledajte [apartmane u Banji Vrujci](/apartmani/banja-vrujci) i celokupnu [ponudu smeštaja](/smestaj), pa upit šaljete direktno vlasniku, bez provizije.\n\n## Šta videti u okolini\n\nVrujci su dobra baza za obilazak Kolubarskog okruga. U blizini su manastir Rajinovac, vrelo i kanjon reke Ribnice, kao i planine Suvobor i Rajac sa uređenim stazama i vidikovcima. Ka Valjevu su čuvene [duvan čvarci i Mišićevi dani](/blog/duvan-cvarci-valjevo-misicevi-dani-mionica), a nešto dalje i Divčibare. Uz kupanje i planinarenje, jednodnevni izleti čine Vrujce pogodnim za produženi vikend.\n\n## Praktičan savet\n\nLeti vikendom bazeni ume da budu popunjeni, pa smeštaj rezervišite ranije i proverite da li je kupanje uključeno u cenu. Ponesite obuću za šetnju — najlepši deo Vrujaca je upravo okolina, a ne samo bazen.",
    body_en: "Banja Vrujci sits in the valley of the Toplica river, in the municipality of Mionica, about an hour and a half south-west of Belgrade. It is known for its moderately warm thermal water, indoor and outdoor pools and a calm, family atmosphere below the Suvobor and Rajac hills. Unlike the large medical spas, Vrujci is above all a place to relax, swim and spend a weekend with children.\n\n## Thermal water and pools\n\nThe springs of Vrujci give water at around 26–28 °C, lightly mineralised and pleasant for bathing all year round. Several complexes around the spa have outdoor pools that open in summer, while some properties have heated indoor pools and small wellness areas. The water is traditionally used to relax muscles and joints, but most guests come simply to swim and unwind.\n\n## When to go\n\nThe main season runs from May to September, when the outdoor pools operate and the surroundings are at their best for walking and cycling. Vrujci is pleasant off-season too: cabins and cottages with their own heating are popular for winter weekends, and the nearby Suvobor and Rajac attract hikers all year.\n\n## Getting there\n\nFrom Belgrade the fastest route is the motorway to Lajkovac, then a local road via Mionica — about 90 to 100 kilometres in total. A car is most practical as it lets you explore the area, but there is also a bus connection to Mionica with local transport to the spa itself. There is more on the options in our piece on [coaches and minibus transport](/en/blog/autoprevoznici-i-kombi-prevoz-srbija-inostranstvo).\n\n## Where to stay\n\nAccommodation in Vrujci is varied: from rooms and apartments in the spa centre to [log cabins](/en/log-cabins) and [holiday cottages](/en/holiday-cottages) on the surrounding hills. Families with children favour properties with their own pool and yard, while cabins outside the centre suit a quieter stay. Browse the full [accommodation offer](/en/accommodation) and send your enquiry directly to the host, with no guest commission.\n\n## What to see nearby\n\nVrujci is a good base for exploring the Kolubara district. Close by are the Rajinovac monastery, the spring and canyon of the Ribnica river, and the Suvobor and Rajac mountains with marked trails and viewpoints. Towards Valjevo lie the famous smoked cracklings and local festivals, and a little further on, Divčibare. With swimming and hiking combined, day trips make Vrujci well suited to a long weekend.\n\n## A practical tip\n\nOn summer weekends the pools can get busy, so book accommodation early and check whether bathing is included in the price. Bring walking shoes — the best part of Vrujci is the surroundings, not just the pool.",
    body_de: "Banja Vrujci liegt im Tal des Flusses Toplica, in der Gemeinde Mionica, etwa anderthalb Autostunden südwestlich von Belgrad. Bekannt ist der Ort für sein mäßig warmes Thermalwasser, Innen- und Außenbecken und eine ruhige, familiäre Atmosphäre unterhalb der Berge Suvobor und Rajac. Anders als die großen Heilbäder ist Vrujci vor allem ein Ort zum Entspannen, Baden und für ein Wochenende mit Kindern.\n\n## Thermalwasser und Becken\n\nDie Quellen von Vrujci liefern Wasser mit etwa 26–28 °C, leicht mineralisiert und ganzjährig angenehm zum Baden. Mehrere Anlagen rund um den Kurort haben Außenbecken, die im Sommer öffnen, während einige Häuser beheizte Innenbecken und kleine Wellnessbereiche bieten. Das Wasser wird traditionell zur Entspannung von Muskeln und Gelenken genutzt, die meisten Gäste kommen jedoch einfach zum Schwimmen und Ausspannen.\n\n## Beste Reisezeit\n\nDie Hauptsaison dauert von Mai bis September, wenn die Außenbecken geöffnet sind und die Umgebung zum Wandern und Radfahren am schönsten ist. Vrujci ist aber auch außerhalb der Saison angenehm: Hütten und Ferienhäuser mit eigener Heizung sind an Winterwochenenden beliebt, und der nahe Suvobor und Rajac ziehen ganzjährig Wanderer an.\n\n## Anreise\n\nAus Belgrad führt die schnellste Route über die Autobahn bis Lajkovac und dann über eine Landstraße via Mionica — insgesamt etwa 90 bis 100 Kilometer. Ein Auto ist am praktischsten, da man so die Umgebung erkunden kann; es gibt aber auch eine Busverbindung nach Mionica mit lokalem Transport zum Kurort. Mehr dazu im Beitrag über [Busse und Minibus-Transport](/de/blog/autoprevoznici-i-kombi-prevoz-srbija-inostranstvo).\n\n## Unterkunft\n\nDas Angebot in Vrujci ist vielfältig: von Zimmern und Apartments im Kurzentrum bis zu [Blockhütten](/de/blockhuetten) und [Ferienhäusern](/de/ferienhaeuser) auf den umliegenden Hügeln. Familien mit Kindern bevorzugen Häuser mit eigenem Pool und Garten, während Hütten außerhalb des Zentrums für einen ruhigeren Aufenthalt geeignet sind. Sehen Sie sich das gesamte [Unterkunftsangebot](/de/unterkunft) an und senden Sie Ihre Anfrage direkt an den Gastgeber, ohne Gästeprovision.\n\n## Ausflüge in der Umgebung\n\nVrujci ist ein guter Ausgangspunkt für den Bezirk Kolubara. In der Nähe liegen das Kloster Rajinovac, die Quelle und der Canyon des Flusses Ribnica sowie die Berge Suvobor und Rajac mit markierten Wegen und Aussichtspunkten. Richtung Valjevo locken die berühmten Tabak-Grieben und lokale Feste, etwas weiter Divčibare. Durch die Kombination aus Baden und Wandern eignet sich Vrujci gut für ein langes Wochenende.\n\n## Praktischer Tipp\n\nAn Sommerwochenenden können die Becken voll werden — buchen Sie die Unterkunft früh und prüfen Sie, ob das Baden im Preis enthalten ist. Nehmen Sie Wanderschuhe mit, denn das Schönste an Vrujci ist die Umgebung, nicht nur das Becken.",
    faq_sr: [
      { q: "Koliko je Banja Vrujci udaljena od Beograda?", a: "Oko 90–100 km, odnosno sat i po vožnje autoputem do Lajkovca pa preko Mionice." },
      { q: "Kolika je temperatura vode u Vrujcima?", a: "Termalna voda je umerene temperature, oko 26–28 °C, prijatna za kupanje tokom cele godine." },
      { q: "Da li su Vrujci pogodni za decu?", a: "Jesu — plitki bazeni, mirno okruženje i smeštaj sa dvorištem čine ih popularnim za porodični odmor." },
    ],
    faq_en: [
      { q: "How far is Banja Vrujci from Belgrade?", a: "About 90–100 km, roughly an hour and a half via the motorway to Lajkovac and then through Mionica." },
      { q: "What is the water temperature in Vrujci?", a: "The thermal water is moderately warm, around 26–28 °C, pleasant for bathing all year round." },
      { q: "Is Vrujci suitable for children?", a: "Yes — shallow pools, calm surroundings and accommodation with yards make it popular for family holidays." },
    ],
    faq_de: [
      { q: "Wie weit ist Banja Vrujci von Belgrad entfernt?", a: "Etwa 90–100 km, rund anderthalb Stunden über die Autobahn bis Lajkovac und dann durch Mionica." },
      { q: "Wie warm ist das Wasser in Vrujci?", a: "Das Thermalwasser ist mäßig warm, etwa 26–28 °C, und ganzjährig angenehm zum Baden." },
      { q: "Ist Vrujci für Kinder geeignet?", a: "Ja — flache Becken, ruhige Umgebung und Unterkünfte mit Garten machen es bei Familien beliebt." },
    ],
  },
];
