import type { Lang } from "@/lib/types";

export type Term = {
  slug: string;
  sr: string; en: string; de: string;        // term
  dsr: string; den: string; dde: string;      // definition
};

export const recnikPath = (lang: Lang) => lang === "sr" ? "/recnik" : lang === "de" ? "/de/glossar" : "/en/glossary";
export const termPath = (slug: string, lang: Lang) => `${recnikPath(lang)}/${slug}`;

export function termLabel(t: Term, lang: Lang) { return lang === "sr" ? t.sr : lang === "de" ? t.de : t.en; }
export function termDef(t: Term, lang: Lang) { return lang === "sr" ? t.dsr : lang === "de" ? t.dde : t.den; }
export const termBySlug = (slug: string) => TERMS.find((t) => t.slug === slug);

export const TERMS: Term[] = [
  { slug: "polupansion", sr: "Polupansion", en: "Half board", de: "Halbpension",
    dsr: "Usluga koja uključuje noćenje, doručak i jedan glavni obrok (najčešće večeru).",
    den: "Accommodation that includes overnight stay, breakfast and one main meal (usually dinner).",
    dde: "Unterkunft mit Übernachtung, Frühstück und einer Hauptmahlzeit (meist Abendessen)." },
  { slug: "pun-pansion", sr: "Pun pansion", en: "Full board", de: "Vollpension",
    dsr: "Usluga koja uključuje noćenje i tri obroka dnevno: doručak, ručak i večeru.",
    den: "Accommodation that includes overnight stay and three meals a day: breakfast, lunch and dinner.",
    dde: "Unterkunft mit Übernachtung und drei Mahlzeiten täglich: Frühstück, Mittag- und Abendessen." },
  { slug: "nocenje-s-doruckom", sr: "Noćenje s doručkom", en: "Bed & breakfast", de: "Übernachtung mit Frühstück",
    dsr: "Usluga koja uključuje samo noćenje i doručak; ostale obroke gost organizuje sam.",
    den: "Service including only overnight stay and breakfast; the guest arranges other meals.",
    dde: "Leistung mit nur Übernachtung und Frühstück; weitere Mahlzeiten organisiert der Gast selbst." },
  { slug: "all-inclusive", sr: "All inclusive", en: "All inclusive", de: "All inclusive",
    dsr: "Usluga gde su svi obroci i većina pića i sadržaja uključeni u cenu boravka.",
    den: "Service where all meals and most drinks and amenities are included in the price.",
    dde: "Leistung, bei der alle Mahlzeiten und die meisten Getränke und Angebote im Preis enthalten sind." },
  { slug: "najam-na-dan", sr: "Izdavanje na dan", en: "Daily rental", de: "Tagesmiete",
    dsr: "Kratkoročno iznajmljivanje smeštaja po danu, bez ugovora o dugoročnom zakupu.",
    den: "Short-term rental of accommodation charged per day, without a long-term lease.",
    dde: "Kurzfristige Vermietung pro Tag, ohne langfristigen Mietvertrag." },
  { slug: "vaucer", sr: "Vaučer", en: "Voucher", de: "Gutschein",
    dsr: "Potvrda o uplaćenoj usluzi koja se predaje pružaocu; u Srbiji i državni vaučer za odmor.",
    den: "A confirmation of a prepaid service handed to the provider; in Serbia also a state holiday voucher.",
    dde: "Bestätigung einer bezahlten Leistung; in Serbien auch ein staatlicher Urlaubsgutschein." },
  { slug: "kapara", sr: "Kapara", en: "Down payment", de: "Anzahlung",
    dsr: "Deo cene koji se plaća unapred radi potvrde rezervacije i odbija se od ukupnog iznosa.",
    den: "Part of the price paid in advance to confirm a booking, deducted from the total.",
    dde: "Im Voraus gezahlter Teilbetrag zur Bestätigung der Buchung, der vom Gesamtpreis abgezogen wird." },
  { slug: "depozit", sr: "Depozit", en: "Security deposit", de: "Kaution",
    dsr: "Povratni iznos koji domaćin uzima kao garanciju za eventualnu štetu i vraća na kraju boravka.",
    den: "A refundable amount the host takes as a guarantee against damage, returned at the end of the stay.",
    dde: "Erstattbarer Betrag als Sicherheit gegen Schäden, der am Ende des Aufenthalts zurückgegeben wird." },
  { slug: "check-in", sr: "Prijava (check-in)", en: "Check-in", de: "Check-in",
    dsr: "Postupak prijave i useljenja gosta u smeštaj, obično u popodnevnim satima.",
    den: "The process of registering and moving the guest into the accommodation, usually in the afternoon.",
    dde: "Anmeldung und Bezug der Unterkunft durch den Gast, meist am Nachmittag." },
  { slug: "check-out", sr: "Odjava (check-out)", en: "Check-out", de: "Check-out",
    dsr: "Postupak odjave i napuštanja smeštaja, obično pre podne na dan odlaska.",
    den: "The process of checking out and leaving the accommodation, usually in the morning of departure.",
    dde: "Abmeldung und Verlassen der Unterkunft, meist am Vormittag des Abreisetags." },
  { slug: "boravisna-taksa", sr: "Boravišna taksa", en: "Tourist tax", de: "Kurtaxe",
    dsr: "Zakonska naknada po osobi i noćenju koju gost plaća lokalnoj samoupravi preko domaćina.",
    den: "A legal fee per person per night that the guest pays to the local authority via the host.",
    dde: "Gesetzliche Gebühr pro Person und Nacht, die der Gast über den Gastgeber an die Gemeinde zahlt." },
  { slug: "minimalni-broj-nocenja", sr: "Minimalni broj noćenja", en: "Minimum nights", de: "Mindestübernachtungen",
    dsr: "Najmanji broj noćenja za koji domaćin prima rezervaciju, čest u sezoni i praznicima.",
    den: "The fewest nights a host accepts for a booking, common in high season and holidays.",
    dde: "Geringste Anzahl an Nächten, die ein Gastgeber akzeptiert, üblich in der Hochsaison und an Feiertagen." },
  { slug: "otkazivanje-rezervacije", sr: "Otkazivanje rezervacije", en: "Cancellation policy", de: "Stornierung",
    dsr: "Pravila pod kojima gost može da otkaže rezervaciju i da li mu se novac vraća.",
    den: "The rules under which a guest may cancel a booking and whether a refund is given.",
    dde: "Regeln, unter denen ein Gast eine Buchung stornieren kann und ob eine Rückerstattung erfolgt." },
  { slug: "no-show", sr: "Nedolazak (no-show)", en: "No-show", de: "No-show",
    dsr: "Situacija kada gost ne dođe na rezervisani termin niti ga otkaže; obično se naplaćuje.",
    den: "When a guest neither arrives for a booking nor cancels it; usually charged.",
    dde: "Wenn ein Gast weder zur Buchung erscheint noch storniert; wird meist berechnet." },
  { slug: "overbooking", sr: "Prekobukiranje (overbooking)", en: "Overbooking", de: "Überbuchung",
    dsr: "Primanje više rezervacija nego što ima slobodnih jedinica, što može dovesti do premeštanja gosta.",
    den: "Accepting more bookings than available units, which can lead to relocating a guest.",
    dde: "Mehr Buchungen annehmen als Einheiten vorhanden sind, was zur Umbuchung eines Gastes führen kann." },
  { slug: "gratis-za-decu", sr: "Gratis za decu", en: "Free for children", de: "Kinder gratis",
    dsr: "Pogodnost gde deca do određene starosti ne plaćaju ili plaćaju umanjenu cenu boravka.",
    den: "A benefit where children up to a certain age stay free or at a reduced price.",
    dde: "Vorteil, bei dem Kinder bis zu einem bestimmten Alter kostenlos oder ermäßigt übernachten." },
  { slug: "pomocni-lezaj", sr: "Pomoćni ležaj", en: "Extra bed", de: "Zustellbett",
    dsr: "Dodatni ležaj koji se ubacuje u sobu na zahtev, najčešće uz doplatu.",
    den: "An additional bed added to a room on request, usually for a surcharge.",
    dde: "Zusätzliches Bett, das auf Wunsch ins Zimmer gestellt wird, meist gegen Aufpreis." },
  { slug: "apartman", sr: "Apartman", en: "Apartment", de: "Apartment",
    dsr: "Smeštajna jedinica sa odvojenom spavaćom sobom, dnevnim boravkom i kuhinjom.",
    den: "An accommodation unit with a separate bedroom, living area and kitchen.",
    dde: "Unterkunft mit getrenntem Schlafzimmer, Wohnbereich und Küche." },
  { slug: "studio", sr: "Studio", en: "Studio", de: "Studio",
    dsr: "Manja jedinica u kojoj su spavaći i dnevni prostor objedinjeni, sa čajnom kuhinjom.",
    den: "A smaller unit where the sleeping and living space are combined, with a kitchenette.",
    dde: "Kleinere Einheit, in der Schlaf- und Wohnbereich kombiniert sind, mit Kochnische." },
  { slug: "garsonjera", sr: "Garsonjera", en: "Studio flat", de: "Garconniere",
    dsr: "Najmanji tip stana sa jednom prostorijom za boravak i spavanje i odvojenim kupatilom.",
    den: "The smallest flat type with one room for living and sleeping and a separate bathroom.",
    dde: "Kleinster Wohnungstyp mit einem Wohn-/Schlafraum und separatem Bad." },
  { slug: "vikendica", sr: "Vikendica", en: "Cottage", de: "Ferienhaus",
    dsr: "Kuća za odmor, obično van grada, koja se izdaje cela jednoj grupi gostiju.",
    den: "A holiday house, usually outside the city, rented as a whole to one group of guests.",
    dde: "Ferienhaus, meist außerhalb der Stadt, das komplett an eine Gästegruppe vermietet wird." },
  { slug: "banja", sr: "Banja", en: "Spa town", de: "Kurort",
    dsr: "Mesto sa termalnim ili mineralnim izvorima i lečilištima, popularno za wellness i oporavak.",
    den: "A place with thermal or mineral springs and health resorts, popular for wellness and recovery.",
    dde: "Ort mit Thermal- oder Mineralquellen und Kurbädern, beliebt für Wellness und Erholung." },
  { slug: "etno-selo", sr: "Etno selo", en: "Ethno village", de: "Ethno-Dorf",
    dsr: "Turistički kompleks u tradicionalnom stilu koji prikazuje narodno graditeljstvo i običaje.",
    den: "A tourist complex in traditional style showcasing folk architecture and customs.",
    dde: "Touristischer Komplex im traditionellen Stil, der Volksarchitektur und Bräuche zeigt." },
  { slug: "glamping", sr: "Glamping", en: "Glamping", de: "Glamping",
    dsr: "Luksuzni kamping sa udobnim šatorima ili kućicama i hotelskim sadržajima u prirodi.",
    den: "Luxury camping with comfortable tents or cabins and hotel-like amenities in nature.",
    dde: "Luxuriöses Camping mit komfortablen Zelten oder Hütten und hotelähnlichem Komfort in der Natur." },
  { slug: "pansion", sr: "Pansion", en: "Guesthouse", de: "Pension",
    dsr: "Manji porodični smeštajni objekat sa nekoliko soba i obično domaćom kuhinjom.",
    den: "A small family-run accommodation with a few rooms and usually home-style cooking.",
    dde: "Kleiner, familiengeführter Beherbergungsbetrieb mit wenigen Zimmern und meist Hausmannskost." },
  { slug: "hostel", sr: "Hostel", en: "Hostel", de: "Hostel",
    dsr: "Povoljan smeštaj sa zajedničkim sobama (dormitorijumima) i deljenim prostorijama.",
    den: "Budget accommodation with shared rooms (dormitories) and communal spaces.",
    dde: "Günstige Unterkunft mit Gemeinschaftszimmern (Schlafsälen) und geteilten Räumen." },
  { slug: "resort", sr: "Resort", en: "Resort", de: "Resort",
    dsr: "Veći kompleks koji na jednom mestu nudi smeštaj, ishranu, zabavu i sportske sadržaje.",
    den: "A larger complex offering accommodation, dining, entertainment and sports in one place.",
    dde: "Größerer Komplex, der Unterkunft, Verpflegung, Unterhaltung und Sport an einem Ort bietet." },
  { slug: "wellness", sr: "Wellness", en: "Wellness", de: "Wellness",
    dsr: "Sadržaji za opuštanje i zdravlje: saune, masaže, bazeni i tretmani lepote.",
    den: "Facilities for relaxation and health: saunas, massages, pools and beauty treatments.",
    dde: "Angebote für Entspannung und Gesundheit: Saunen, Massagen, Pools und Schönheitsbehandlungen." },
  { slug: "transfer", sr: "Transfer", en: "Transfer", de: "Transfer",
    dsr: "Organizovani prevoz gostiju, najčešće od aerodroma ili stanice do smeštaja i nazad.",
    den: "Organized transport of guests, usually from the airport or station to the accommodation and back.",
    dde: "Organisierter Transport der Gäste, meist vom Flughafen oder Bahnhof zur Unterkunft und zurück." },
  { slug: "aranzman", sr: "Aranžman", en: "Travel package", de: "Reisepaket",
    dsr: "Paket-usluga koja u jednu cenu spaja prevoz, smeštaj i često ishranu i izlete.",
    den: "A package combining transport, accommodation and often meals and excursions in one price.",
    dde: "Paket, das Transport, Unterkunft und oft Verpflegung und Ausflüge zu einem Preis verbindet." },
  { slug: "first-minute", sr: "First minute", en: "First minute", de: "Frühbucher",
    dsr: "Popust za rezervacije napravljene davno unapred, pre glavne sezone.",
    den: "A discount for bookings made well in advance, before the main season.",
    dde: "Rabatt für Buchungen, die lange im Voraus vor der Hauptsaison getätigt werden." },
  { slug: "last-minute", sr: "Last minute", en: "Last minute", de: "Last Minute",
    dsr: "Sniženje za rezervacije neposredno pred polazak radi popunjavanja slobodnih mesta.",
    den: "A reduction for bookings shortly before departure to fill remaining places.",
    dde: "Ermäßigung für Buchungen kurz vor der Abreise, um freie Plätze zu füllen." },
  { slug: "fakultativni-izlet", sr: "Fakultativni izlet", en: "Optional excursion", de: "Fakultativer Ausflug",
    dsr: "Dodatni izlet koji nije uključen u cenu aranžmana i plaća se posebno, po želji.",
    den: "An extra excursion not included in the package price, paid separately and optional.",
    dde: "Zusätzlicher Ausflug, der nicht im Reisepreis enthalten ist und optional extra bezahlt wird." },
  { slug: "vodic", sr: "Vodič", en: "Tour guide", de: "Reiseleiter",
    dsr: "Stručna osoba koja prati grupu i tumači znamenitosti tokom putovanja ili obilaska.",
    den: "A professional who accompanies a group and explains the sights during a trip or tour.",
    dde: "Fachperson, die eine Gruppe begleitet und die Sehenswürdigkeiten während der Reise erklärt." },
  { slug: "itinerer", sr: "Itinerer", en: "Itinerary", de: "Reiseroute",
    dsr: "Detaljan plan putovanja sa redosledom destinacija, vremenima i aktivnostima.",
    den: "A detailed travel plan with the order of destinations, times and activities.",
    dde: "Detaillierter Reiseplan mit der Reihenfolge der Ziele, Zeiten und Aktivitäten." },
  { slug: "visoka-sezona", sr: "Visoka sezona", en: "High season", de: "Hochsaison",
    dsr: "Period najveće tražnje i najviših cena, npr. leto na jezerima ili zima na planinama.",
    den: "The period of highest demand and prices, e.g. summer at the lakes or winter in the mountains.",
    dde: "Zeit der höchsten Nachfrage und Preise, z. B. Sommer an den Seen oder Winter in den Bergen." },
  { slug: "vansezona", sr: "Vansezona", en: "Off season", de: "Nebensaison",
    dsr: "Period slabije tražnje sa nižim cenama i mirnijim destinacijama.",
    den: "A period of lower demand with lower prices and quieter destinations.",
    dde: "Zeit geringerer Nachfrage mit niedrigeren Preisen und ruhigeren Zielen." },
  { slug: "putno-osiguranje", sr: "Putno osiguranje", en: "Travel insurance", de: "Reiseversicherung",
    dsr: "Osiguranje koje pokriva troškove lečenja, otkaza ili gubitka prtljaga tokom putovanja.",
    den: "Insurance covering medical costs, cancellation or lost luggage during travel.",
    dde: "Versicherung, die Krankheitskosten, Stornierung oder Gepäckverlust auf Reisen abdeckt." },
  { slug: "predracun", sr: "Predračun", en: "Proforma invoice", de: "Proformarechnung",
    dsr: "Dokument sa iznosom za uplatu pre izvršenja usluge; nije fiskalni račun.",
    den: "A document stating the amount to pay before the service is performed; not a fiscal receipt.",
    dde: "Dokument mit dem zu zahlenden Betrag vor Leistungserbringung; keine Fiskalrechnung." },
  { slug: "domacin", sr: "Domaćin", en: "Host", de: "Gastgeber",
    dsr: "Vlasnik ili upravnik smeštaja koji prima goste i pruža uslugu boravka.",
    den: "The owner or manager of the accommodation who receives guests and provides the stay.",
    dde: "Eigentümer oder Verwalter der Unterkunft, der Gäste empfängt und den Aufenthalt anbietet." },
  { slug: "kucni-ljubimci-dozvoljeni", sr: "Kućni ljubimci dozvoljeni", en: "Pets allowed", de: "Haustiere erlaubt",
    dsr: "Oznaka da smeštaj prima goste sa kućnim ljubimcima, ponekad uz doplatu ili pravila.",
    den: "An indication that the accommodation accepts guests with pets, sometimes with a fee or rules.",
    dde: "Hinweis, dass die Unterkunft Gäste mit Haustieren akzeptiert, teils gegen Gebühr oder mit Regeln." },
];
